spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding-databases.yml

  jpa:
    hibernate:
      ddl-auto: none  # Disable automatic schema generation; use Flyway/Liquibase
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect    # Adjust to your DB type/version

logging:
  level:
    root: INFO
    org.apache.shardingsphere: INFO
  file:
    name: application.log
